### ISSUE TITLE
Better name for this package? 

### ISSUE THREAD

**Issue by aviks** [tanmaykm/JuliaWebAPI.jl#5]
JuliaBox.jl is a very confusing name for this package, and prevents discovery. We should rename it to something more relevant. 

Some suggestions include: 

APIBox.jl
Serve.jl
APIServe.jl

cc: @viralbshah

**Comment by ViralBShah** [comment]
I like APIBox.jl. Let's do this - others are also asking for it.

**Comment by EricForgy** [comment]
Hi guys,

I came here to file this exact issue: better name :)

JuliaBox is probably better to refer to [https://juliabox.org/](https://juliabox.org/).

In [this](https://groups.google.com/d/msg/julia-users/Hw7pROPKyqI/HsS7bI__BmAJ) comment, Viral recommend JuliaRemoteAPI.jl.

I would probably prefer something like that with the word "Julia" in it because it is an API for Julia itself.

Off the top of my head:

* JuliaRemoteAPI.jl
* JuliaAPI.jl
* JuliaWebAPI.
* JuliaServerAPI.jl
* JuliaServer.jl

Looking at those, my favorite is JuliaServer.jl. What do you think?

**Comment by ViralBShah** [comment]
I like JuliaWebAPI.jl, since that is exactly what this is. There could be many other JuliaServer packages.

**Comment by EricForgy** [comment]
Where is the "Like" button? :+1: :)

JuliaWebAPI sounds good to me too.

**Comment by tanmaykm** [comment]
I like JuliaWebAPI.jl too.
Will rename it soon, unless there are other views.
